table fact_procedures
	lineageTag: c4bf554b-f3c5-4168-b922-d9d682ef678e
	sourceLineageTag: [healthcare].[fact_procedures]

	measure 'Last Procedures Date' =
			LASTNONBLANK (
			'dim_date'[full_date],
			CALCULATE ( COUNTROWS ( fact_procedures ) )
			)
		lineageTag: 09fb709e-6abe-4561-8af0-be9aa7809f45

	measure 'Total Procedures' = COUNTROWS ( fact_procedures )
		lineageTag: b3578d96-7731-4f10-93cd-43852edad9e5

	measure 'Procedures YTD' =
			VAR _refDate = [Last Procedures Date]
			RETURN
			CALCULATE (
			[Total Procedures],
			DATESBETWEEN (
			'dim_date'[full_date],
			DATE ( YEAR ( _refDate ), 1, 1 ),
			_refDate
			)
			)
		lineageTag: d57081c2-b31b-4cae-b715-5b963d381620

	measure 'Procedures MTD' =
			VAR _refDate = [Last Procedures Date]
			RETURN
			CALCULATE (
			[Total Procedures],
			DATESBETWEEN (
			'dim_date'[full_date],
			EOMONTH ( _refDate, -1 ) + 1,
			_refDate
			)
			)
		lineageTag: c2cae73f-15a2-4767-817d-4539a9015acf

	measure 'Total Procedures LY' =
			VAR _refDate = [Last Procedures Date]
			RETURN
			CALCULATE (
			[Total Procedures],
			DATESBETWEEN (
			'dim_date'[full_date],
			DATE ( YEAR ( _refDate ) - 1, 1, 1 ),
			EDATE ( _refDate, -12 )
			)
			)
		lineageTag: 78dcff08-3bc9-4fb7-9e6d-7be3194f7c88

	measure 'Procedures YoY %' =
			DIVIDE (
			[Total Procedures] - [Total Procedures LY],
			[Total Procedures LY],
			BLANK ()
			)
		lineageTag: f82320f2-e53b-40b0-be2c-a30c611db5ce

	measure 'Total Charge Amount' = SUM ( fact_procedures[charge_amount] )
		lineageTag: 96bd574f-d3e2-434b-8b07-8716768e10d7

	measure 'Avg Charge Amount' = AVERAGE ( fact_procedures[charge_amount] )
		lineageTag: 84022c4a-3d22-401d-812b-de26a37e4749

	measure 'Charge Amount YTD' =
			VAR _refDate = [Last Procedures Date]
			RETURN
			CALCULATE (
			[Total Charge Amount],
			DATESBETWEEN (
			'dim_date'[full_date],
			DATE ( YEAR ( _refDate ), 1, 1 ),
			_refDate
			)
			)
		lineageTag: e65926d3-5209-470a-bb7c-2c011debcc84

	measure 'Total Charge Amount LY' =
			VAR _refDate = [Last Procedures Date]
			RETURN
			CALCULATE (
			[Total Charge Amount],
			DATESBETWEEN (
			'dim_date'[full_date],
			DATE ( YEAR ( _refDate ) - 1, 1, 1 ),
			EDATE ( _refDate, -12 )
			)
			)
		lineageTag: 5d4bac7e-6ead-4d52-8a8d-e109ec9e3c07

	measure 'Charge Amount YoY %' =
			DIVIDE (
			[Total Charge Amount] - [Total Charge Amount LY],
			[Total Charge Amount LY],
			BLANK ()
			)
		lineageTag: d9d7637c-db0d-4b92-afa7-eed11950eec7

	measure 'Charge Amount 3M Rolling' =
			VAR _refDate = [Last Procedures Date]
			RETURN
			CALCULATE (
			[Total Charge Amount],
			DATESINPERIOD (
			'dim_date'[full_date],
			_refDate,
			-3,
			MONTH
			)
			)
		lineageTag: 92562fc6-a191-44b1-b288-61e701c1d481

	measure 'Total Total Charge' = SUM ( fact_procedures[total_charge] )
		lineageTag: 2e0d835c-4e5d-48cf-839a-5d80df3342d0

	measure 'Avg Total Charge' = AVERAGE ( fact_procedures[total_charge] )
		lineageTag: d4d62f0a-de57-4550-9ae3-8a0df7d3a7c0

	measure 'Total Charge YTD' =
			VAR _refDate = [Last Procedures Date]
			RETURN
			CALCULATE (
			[Total Total Charge],
			DATESBETWEEN (
			'dim_date'[full_date],
			DATE ( YEAR ( _refDate ), 1, 1 ),
			_refDate
			)
			)
		lineageTag: d98f9727-aa57-46ef-af77-0df07322d0cb

	measure 'Total Total Charge LY' =
			VAR _refDate = [Last Procedures Date]
			RETURN
			CALCULATE (
			[Total Total Charge],
			DATESBETWEEN (
			'dim_date'[full_date],
			DATE ( YEAR ( _refDate ) - 1, 1, 1 ),
			EDATE ( _refDate, -12 )
			)
			)
		lineageTag: e947dcb5-09da-4d01-9ec7-a50e1f937b38

	measure 'Total Charge YoY %' =
			DIVIDE (
			[Total Total Charge] - [Total Total Charge LY],
			[Total Total Charge LY],
			BLANK ()
			)
		lineageTag: 885d4dc6-e051-4271-9459-8f06b14170c3

	measure 'Total Charge 3M Rolling' =
			VAR _refDate = [Last Procedures Date]
			RETURN
			CALCULATE (
			[Total Total Charge],
			DATESINPERIOD (
			'dim_date'[full_date],
			_refDate,
			-3,
			MONTH
			)
			)
		lineageTag: eeed5df3-c834-4cc8-8e05-c3c113150d60

	column fact_procedure_sk
		dataType: int64
		formatString: 0
		lineageTag: 215cddc9-051d-4304-a389-c6d87c488346
		sourceLineageTag: fact_procedure_sk
		summarizeBy: none
		sourceColumn: fact_procedure_sk

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 185841c0-351d-4cda-b3e4-7a5b150e6f78
		sourceLineageTag: date_key
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column provider_sk
		dataType: int64
		formatString: 0
		lineageTag: 59911bc3-64c3-4f25-9869-2b4cd4a746d3
		sourceLineageTag: provider_sk
		summarizeBy: none
		sourceColumn: provider_sk

		annotation SummarizationSetBy = Automatic

	column procedure_id
		dataType: int64
		formatString: 0
		lineageTag: 16231b67-145b-461e-850c-f9fc66e358e7
		sourceLineageTag: procedure_id
		summarizeBy: none
		sourceColumn: procedure_id

		annotation SummarizationSetBy = Automatic

	column procedure_code
		dataType: string
		lineageTag: 1ef1cbe7-5545-4197-8a3b-4b82573e9de2
		sourceLineageTag: procedure_code
		summarizeBy: none
		sourceColumn: procedure_code

		annotation SummarizationSetBy = Automatic

	column encounter_id
		dataType: int64
		formatString: 0
		lineageTag: 58b3694e-514c-44bc-8d65-06bdd72f4d15
		sourceLineageTag: encounter_id
		summarizeBy: none
		sourceColumn: encounter_id

		annotation SummarizationSetBy = Automatic

	column cpt_code
		dataType: string
		lineageTag: cc0964e4-edcd-46ff-93fb-0be1edcc93b8
		sourceLineageTag: cpt_code
		summarizeBy: none
		sourceColumn: cpt_code

		annotation SummarizationSetBy = Automatic

	column procedure_description
		dataType: string
		lineageTag: f624eb9a-7974-414d-b8d0-676798172a34
		sourceLineageTag: procedure_description
		summarizeBy: none
		sourceColumn: procedure_description

		annotation SummarizationSetBy = Automatic

	column procedure_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 11e47381-cd2a-4ba4-b072-fbdd31f918de
		sourceLineageTag: procedure_date
		summarizeBy: none
		sourceColumn: procedure_date

		annotation SummarizationSetBy = Automatic

	column procedure_status
		dataType: string
		lineageTag: 59cda13c-a471-40f1-a86c-eb26a162b6df
		sourceLineageTag: procedure_status
		summarizeBy: none
		sourceColumn: procedure_status

		annotation SummarizationSetBy = Automatic

	column units
		dataType: int64
		formatString: 0
		lineageTag: a28e5fba-31ec-442f-9a84-8c0df1da7e06
		sourceLineageTag: units
		summarizeBy: sum
		sourceColumn: units

		annotation SummarizationSetBy = Automatic

	column charge_amount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 09057aef-9cac-44d3-a8e7-8b504a1fc928
		sourceLineageTag: charge_amount
		summarizeBy: sum
		sourceColumn: charge_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column total_charge
		dataType: double
		lineageTag: 1daaf47d-f897-406a-bfe8-8201dfb640cd
		sourceLineageTag: total_charge
		summarizeBy: sum
		sourceColumn: total_charge

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_procedures = entity
		mode: directLake
		source
			entityName: fact_procedures
			schemaName: healthcare
			expressionSource: 'DirectLake - GoldLH'

