table fact_encounters
	lineageTag: 85edf9e7-c27b-4706-aa96-30af1b83d855
	sourceLineageTag: [healthcare].[fact_encounters]

	measure 'Last Encounters Date' =
			LASTNONBLANK (
			'dim_date'[full_date],
			CALCULATE ( COUNTROWS ( fact_encounters ) )
			)
		lineageTag: d7cdef31-2162-418c-8545-3a1043980c8d

	measure 'Total Encounters' = COUNTROWS ( fact_encounters )
		lineageTag: b494e010-738e-46a9-8ec1-f3160364463b

	measure 'Encounters YTD' =
			VAR _refDate = [Last Encounters Date]
			RETURN
			CALCULATE (
			[Total Encounters],
			DATESBETWEEN (
			'dim_date'[full_date],
			DATE ( YEAR ( _refDate ), 1, 1 ),
			_refDate
			)
			)
		lineageTag: d4a7e34c-19f6-4a13-a9fa-283c95d77f18

	measure 'Encounters MTD' =
			VAR _refDate = [Last Encounters Date]
			RETURN
			CALCULATE (
			[Total Encounters],
			DATESBETWEEN (
			'dim_date'[full_date],
			EOMONTH ( _refDate, -1 ) + 1,
			_refDate
			)
			)
		lineageTag: c60aab6b-6626-4f87-9464-9e5d30e560f3

	measure 'Total Encounters LY' =
			VAR _refDate = [Last Encounters Date]
			RETURN
			CALCULATE (
			[Total Encounters],
			DATESBETWEEN (
			'dim_date'[full_date],
			DATE ( YEAR ( _refDate ) - 1, 1, 1 ),
			EDATE ( _refDate, -12 )
			)
			)
		lineageTag: b0773420-51f3-44db-8d16-0f4f022034ae

	measure 'Encounters YoY %' =
			DIVIDE (
			[Total Encounters] - [Total Encounters LY],
			[Total Encounters LY],
			BLANK ()
			)
		lineageTag: efce56a9-b101-4bec-bb06-7b5e04624cc0

	measure 'Total Total Charges' = SUM ( fact_encounters[total_charges] )
		lineageTag: 2c5e77ae-1c9b-4513-9953-53e15b7cc18f

	measure 'Avg Total Charges' = AVERAGE ( fact_encounters[total_charges] )
		lineageTag: c6455548-6531-4a62-b2fa-9050fe202af6

	measure 'Total Charges YTD' =
			VAR _refDate = [Last Encounters Date]
			RETURN
			CALCULATE (
			[Total Total Charges],
			DATESBETWEEN (
			'dim_date'[full_date],
			DATE ( YEAR ( _refDate ), 1, 1 ),
			_refDate
			)
			)
		lineageTag: 3ed42bd2-5300-474b-8bc4-47c972d76053

	measure 'Total Total Charges LY' =
			VAR _refDate = [Last Encounters Date]
			RETURN
			CALCULATE (
			[Total Total Charges],
			DATESBETWEEN (
			'dim_date'[full_date],
			DATE ( YEAR ( _refDate ) - 1, 1, 1 ),
			EDATE ( _refDate, -12 )
			)
			)
		lineageTag: 7ef63d98-7f7b-4284-9e8a-3e9b8c712482

	measure 'Total Charges YoY %' =
			DIVIDE (
			[Total Total Charges] - [Total Total Charges LY],
			[Total Total Charges LY],
			BLANK ()
			)
		lineageTag: 0c710621-87b8-4136-a6ae-e46c112bb6ad

	measure 'Total Charges 3M Rolling' =
			VAR _refDate = [Last Encounters Date]
			RETURN
			CALCULATE (
			[Total Total Charges],
			DATESINPERIOD (
			'dim_date'[full_date],
			_refDate,
			-3,
			MONTH
			)
			)
		lineageTag: 4dbd1be6-21ea-4359-85aa-2de948f60363

	column fact_encounter_sk
		dataType: int64
		formatString: 0
		lineageTag: 149158c1-40ba-4ac9-bc7c-92d3724fe11f
		sourceLineageTag: fact_encounter_sk
		summarizeBy: none
		sourceColumn: fact_encounter_sk

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 7e083617-c28a-496d-86a7-cdf080cb9b99
		sourceLineageTag: date_key
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column patient_sk
		dataType: int64
		formatString: 0
		lineageTag: 80a68b39-d97c-4499-9593-bbe1a48528aa
		sourceLineageTag: patient_sk
		summarizeBy: none
		sourceColumn: patient_sk

		annotation SummarizationSetBy = Automatic

	column provider_sk
		dataType: int64
		formatString: 0
		lineageTag: 441f7955-acc8-4e7c-9817-1ab8c1162492
		sourceLineageTag: provider_sk
		summarizeBy: none
		sourceColumn: provider_sk

		annotation SummarizationSetBy = Automatic

	column encounter_id
		dataType: int64
		formatString: 0
		lineageTag: 20991f02-b564-4c94-ab6b-460bfc515a46
		sourceLineageTag: encounter_id
		summarizeBy: none
		sourceColumn: encounter_id

		annotation SummarizationSetBy = Automatic

	column encounter_code
		dataType: string
		lineageTag: 2e4e6e64-7a95-4674-a27a-47107ae922df
		sourceLineageTag: encounter_code
		summarizeBy: none
		sourceColumn: encounter_code

		annotation SummarizationSetBy = Automatic

	column admit_date
		dataType: dateTime
		formatString: General Date
		lineageTag: c1f1d71c-8518-4cc0-88b9-4252c002cae9
		sourceLineageTag: admit_date
		summarizeBy: none
		sourceColumn: admit_date

		annotation SummarizationSetBy = Automatic

	column discharge_date
		dataType: dateTime
		formatString: General Date
		lineageTag: ad9b3320-987e-46f8-b730-77469b5eb6c0
		sourceLineageTag: discharge_date
		summarizeBy: none
		sourceColumn: discharge_date

		annotation SummarizationSetBy = Automatic

	column encounter_type
		dataType: string
		lineageTag: 5ba3fc9d-15c7-49cf-838a-4a6e3a854c7a
		sourceLineageTag: encounter_type
		summarizeBy: none
		sourceColumn: encounter_type

		annotation SummarizationSetBy = Automatic

	column admission_source
		dataType: string
		lineageTag: e593b9ed-dd3f-4e8d-9003-79c2086585fc
		sourceLineageTag: admission_source
		summarizeBy: none
		sourceColumn: admission_source

		annotation SummarizationSetBy = Automatic

	column discharge_disposition
		dataType: string
		lineageTag: 717c7653-0255-46af-b2e9-033772de9722
		sourceLineageTag: discharge_disposition
		summarizeBy: none
		sourceColumn: discharge_disposition

		annotation SummarizationSetBy = Automatic

	column appointment_id
		dataType: int64
		formatString: 0
		lineageTag: ef6ef473-cf81-499e-bf55-95bfde3768eb
		sourceLineageTag: appointment_id
		summarizeBy: none
		sourceColumn: appointment_id

		annotation SummarizationSetBy = Automatic

	column facility_code
		dataType: string
		lineageTag: 82c7024d-69c3-492b-84a7-d921364b1b86
		sourceLineageTag: facility_code
		summarizeBy: none
		sourceColumn: facility_code

		annotation SummarizationSetBy = Automatic

	column length_of_stay_days
		dataType: int64
		formatString: 0
		lineageTag: 5c1b89e2-92e8-4221-9093-bfe1076a9856
		sourceLineageTag: length_of_stay_days
		summarizeBy: sum
		sourceColumn: length_of_stay_days

		annotation SummarizationSetBy = Automatic

	column total_charges
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: f1eca78b-9ec5-4414-9bc2-4f4425b89c84
		sourceLineageTag: total_charges
		summarizeBy: sum
		sourceColumn: total_charges

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition fact_encounters = entity
		mode: directLake
		source
			entityName: fact_encounters
			schemaName: healthcare
			expressionSource: 'DirectLake - GoldLH'

