table fact_diagnoses
	lineageTag: 3ca0fa66-0c9b-4c4b-bbf4-20befb8bb4fa
	sourceLineageTag: [healthcare].[fact_diagnoses]

	measure 'Last Diagnoses Date' =
			LASTNONBLANK (
			'dim_date'[full_date],
			CALCULATE ( COUNTROWS ( fact_diagnoses ) )
			)
		lineageTag: 5f68cc7a-1531-449c-b072-28ad1a5c71c2

	measure 'Total Diagnoses' = COUNTROWS ( fact_diagnoses )
		lineageTag: 5f055b16-3914-4cab-8b80-2a4bc50becc4

	measure 'Diagnoses YTD' =
			VAR _refDate = [Last Diagnoses Date]
			RETURN
			CALCULATE (
			[Total Diagnoses],
			DATESBETWEEN (
			'dim_date'[full_date],
			DATE ( YEAR ( _refDate ), 1, 1 ),
			_refDate
			)
			)
		lineageTag: e9b9eebb-c63e-418b-8efc-47e955f6064c

	measure 'Diagnoses MTD' =
			VAR _refDate = [Last Diagnoses Date]
			RETURN
			CALCULATE (
			[Total Diagnoses],
			DATESBETWEEN (
			'dim_date'[full_date],
			EOMONTH ( _refDate, -1 ) + 1,
			_refDate
			)
			)
		lineageTag: 9b536a41-51c4-4797-8a3a-0a55805cad42

	measure 'Total Diagnoses LY' =
			VAR _refDate = [Last Diagnoses Date]
			RETURN
			CALCULATE (
			[Total Diagnoses],
			DATESBETWEEN (
			'dim_date'[full_date],
			DATE ( YEAR ( _refDate ) - 1, 1, 1 ),
			EDATE ( _refDate, -12 )
			)
			)
		lineageTag: d23be0ac-a437-45a0-9dd2-46216ddd2c90

	measure 'Diagnoses YoY %' =
			DIVIDE (
			[Total Diagnoses] - [Total Diagnoses LY],
			[Total Diagnoses LY],
			BLANK ()
			)
		lineageTag: 954389e1-2409-47b8-acc9-2fa754fe8e0f

	column fact_diagnosis_sk
		dataType: int64
		formatString: 0
		lineageTag: c1be2d3c-f6dc-4751-ad27-3fae1729f3c1
		sourceLineageTag: fact_diagnosis_sk
		summarizeBy: none
		sourceColumn: fact_diagnosis_sk

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: f28b5031-2db0-464b-8d65-1011a1599d41
		sourceLineageTag: date_key
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column encounter_id
		dataType: int64
		formatString: 0
		lineageTag: 9b39faca-a31d-44b5-89b2-805cd13b1d42
		sourceLineageTag: encounter_id
		summarizeBy: none
		sourceColumn: encounter_id

		annotation SummarizationSetBy = Automatic

	column diagnosis_id
		dataType: int64
		formatString: 0
		lineageTag: f11b1d7d-8d12-4ac3-87f0-30ea5a862cec
		sourceLineageTag: diagnosis_id
		summarizeBy: none
		sourceColumn: diagnosis_id

		annotation SummarizationSetBy = Automatic

	column icd_10_code
		dataType: string
		lineageTag: c342f9fd-fb28-42b8-b17c-ed01b3f26e3e
		sourceLineageTag: icd_10_code
		summarizeBy: none
		sourceColumn: icd_10_code

		annotation SummarizationSetBy = Automatic

	column diagnosis_description
		dataType: string
		lineageTag: c0428e4c-fba7-44ee-a4ad-9ca4ed2a47e5
		sourceLineageTag: diagnosis_description
		summarizeBy: none
		sourceColumn: diagnosis_description

		annotation SummarizationSetBy = Automatic

	column diagnosis_type
		dataType: string
		lineageTag: d3cca71b-f940-49b7-97ed-e2d9ead01143
		sourceLineageTag: diagnosis_type
		summarizeBy: none
		sourceColumn: diagnosis_type

		annotation SummarizationSetBy = Automatic

	column severity
		dataType: string
		lineageTag: b6d7b982-72db-46b8-ad59-419f87445104
		sourceLineageTag: severity
		summarizeBy: none
		sourceColumn: severity

		annotation SummarizationSetBy = Automatic

	partition fact_diagnoses = entity
		mode: directLake
		source
			entityName: fact_diagnoses
			schemaName: healthcare
			expressionSource: 'DirectLake - GoldLH'

